import Foundation
import SwiftUI

/// A dynamic widget generated by the LLM for the insights dashboard.
/// The LLM returns a JSON array of these; SwiftUI renders them by type.
struct DynamicWidget: Identifiable, Sendable {
    let id: UUID
    let type: WidgetType
    let title: String?
    let icon: String?
    let color: String?
    let priority: Int

    // Payloads — only the one matching `type` is non-nil
    let stat: StatPayload?
    let list: ListPayload?
    let quote: QuotePayload?
    let alert: AlertPayload?
    let progress: ProgressPayload?
    let markdown: MarkdownPayload?
    let kv: KVPayload?
    let timeline: TimelinePayload?
    let barChart: BarChartPayload?

    var resolvedColor: Color {
        guard let color else { return .secondary }
        switch color.lowercased() {
        case "red": return .red
        case "orange": return .orange
        case "yellow": return .yellow
        case "green": return .green
        case "blue": return .blue
        case "purple": return .purple
        case "pink": return .pink
        case "teal": return .teal
        case "cyan": return .cyan
        case "indigo": return .indigo
        case "mint": return .mint
        default: return .secondary
        }
    }

    enum WidgetType: String, Codable, Sendable {
        case stat
        case list
        case quote
        case alert
        case progress
        case markdown
        case kv
        case timeline
        case barChart = "bar_chart"
    }

    struct StatPayload: Codable, Sendable {
        let value: String
        let label: String
        let trend: String?
    }

    struct ListPayload: Codable, Sendable {
        let items: [String]
    }

    struct QuotePayload: Codable, Sendable {
        let text: String
        let speaker: String?
        let annotation: String?
    }

    struct AlertPayload: Codable, Sendable {
        let severity: String?
        let message: String
    }

    struct ProgressPayload: Codable, Sendable {
        let items: [ProgressItem]
        struct ProgressItem: Codable, Sendable {
            let label: String
            let done: Bool
        }
    }

    struct MarkdownPayload: Codable, Sendable {
        let content: String
    }

    struct KVPayload: Codable, Sendable {
        let pairs: [KVPair]
        struct KVPair: Codable, Sendable {
            let key: String
            let value: String
        }
    }

    struct TimelinePayload: Codable, Sendable {
        let events: [TimelineEvent]
        struct TimelineEvent: Codable, Sendable {
            let time: String
            let desc: String
        }
    }

    struct BarChartPayload: Codable, Sendable {
        let bars: [Bar]
        struct Bar: Codable, Sendable {
            let label: String
            let value: Double
        }
    }
}

// MARK: - JSON Decoding (from LLM output)

extension DynamicWidget {

    /// Raw JSON structure the LLM returns. Flat with optional payload fields.
    private struct RawWidget: Codable {
        let type: String
        let title: String?
        let icon: String?
        let color: String?
        let priority: Int?

        // Stat
        let value: String?
        let label: String?
        let trend: String?

        // List
        let items: AnyCodableItems?

        // Quote
        let text: String?
        let speaker: String?
        let annotation: String?

        // Alert
        let severity: String?
        let message: String?

        // Markdown
        let content: String?

        // KV
        let pairs: [KVPayload.KVPair]?

        // Timeline
        let events: [TimelinePayload.TimelineEvent]?

        // Bar chart
        let bars: [BarChartPayload.Bar]?
    }

    /// Items can be either `[String]` or `[{label, done}]` depending on widget type.
    private enum AnyCodableItems: Codable {
        case strings([String])
        case progressItems([ProgressPayload.ProgressItem])

        init(from decoder: Decoder) throws {
            let container = try decoder.singleValueContainer()
            if let items = try? container.decode([ProgressPayload.ProgressItem].self) {
                self = .progressItems(items)
            } else if let items = try? container.decode([String].self) {
                self = .strings(items)
            } else {
                self = .strings([])
            }
        }

        func encode(to encoder: Encoder) throws {
            var container = encoder.singleValueContainer()
            switch self {
            case .strings(let s): try container.encode(s)
            case .progressItems(let p): try container.encode(p)
            }
        }
    }

    /// Parse a JSON array of widgets from LLM output.
    static func parse(from text: String) -> [DynamicWidget] {
        guard let rawWidgets = try? LLMJSONParser.extract([RawWidget].self, from: text) else {
            return []
        }
        return rawWidgets.compactMap { raw in
            guard let widgetType = WidgetType(rawValue: raw.type) else { return nil }

            var stat: StatPayload?
            var list: ListPayload?
            var quote: QuotePayload?
            var alert: AlertPayload?
            var progress: ProgressPayload?
            var markdown: MarkdownPayload?
            var kv: KVPayload?
            var timeline: TimelinePayload?
            var barChart: BarChartPayload?

            switch widgetType {
            case .stat:
                guard let v = raw.value, let l = raw.label else { return nil }
                stat = StatPayload(value: v, label: l, trend: raw.trend)
            case .list:
                if case .strings(let items) = raw.items {
                    list = ListPayload(items: items)
                } else { return nil }
            case .quote:
                guard let t = raw.text else { return nil }
                quote = QuotePayload(text: t, speaker: raw.speaker, annotation: raw.annotation)
            case .alert:
                guard let m = raw.message else { return nil }
                alert = AlertPayload(severity: raw.severity, message: m)
            case .progress:
                if case .progressItems(let items) = raw.items {
                    progress = ProgressPayload(items: items)
                } else { return nil }
            case .markdown:
                guard let c = raw.content else { return nil }
                markdown = MarkdownPayload(content: c)
            case .kv:
                guard let p = raw.pairs else { return nil }
                kv = KVPayload(pairs: p)
            case .timeline:
                guard let e = raw.events else { return nil }
                timeline = TimelinePayload(events: e)
            case .barChart:
                guard let b = raw.bars else { return nil }
                barChart = BarChartPayload(bars: b)
            }

            return DynamicWidget(
                id: UUID(),
                type: widgetType,
                title: raw.title,
                icon: raw.icon,
                color: raw.color,
                priority: raw.priority ?? 0,
                stat: stat,
                list: list,
                quote: quote,
                alert: alert,
                progress: progress,
                markdown: markdown,
                kv: kv,
                timeline: timeline,
                barChart: barChart
            )
        }
    }
}
